# Generated by Django 5.2.4 on 2025-09-18 03:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Links", max_length=100)),
                ("subtitle", models.CharField(max_length=255)),
                (
                    "anh_dai_dien",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("loai", models.IntegerField(default=0)),
                ("tinh_trang", models.IntegerField(default=0)),
                ("links", models.TextField()),
            ],
            options={
                "verbose_name": "Link Profile",
                "verbose_name_plural": "Link Profiles",
            },
        ),
        migrations.CreateModel(
            name="LoaiSanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_loai", models.CharField(max_length=100, unique=True)),
                ("tinh_trang", models.IntegerField(default=0)),
                ("layout", models.IntegerField(default=0)),
                ("link_danh_muc", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        help_text="Màu nền chung (hex)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StyleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "font_family",
                    models.CharField(
                        blank=True,
                        help_text="Font family CSS",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        blank=True,
                        help_text="Font weight (px, em, rem)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        help_text="Màu nền chung (hex)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Màu chữ (hex)", max_length=20, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_name",
                    models.CharField(default="homepage", max_length=100, unique=True),
                ),
                ("total_visits", models.IntegerField(default=0)),
                ("today_visits", models.IntegerField(default=0)),
                (
                    "last_visit_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "visit_counter",
            },
        ),
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("so_dien_thoai", models.CharField(max_length=20)),
                ("ho_va_ten", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=128)),
                ("hash_reset", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hash_active",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.IntegerField(default=0)),
                ("is_block", models.IntegerField(default=0)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkClickHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.linkprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_san_pham", models.CharField(max_length=255)),
                ("duong_dan_ngoai", models.URLField(blank=True, null=True)),
                ("gia_mac_dinh", models.CharField(max_length=50)),
                ("tinh_trang", models.IntegerField(default=0)),
                (
                    "anh_dai_dien",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "loai_san_pham",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="san_phams",
                        to="core.loaisanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanPhamView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("page_visited", models.CharField(max_length=100)),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "visit_logs",
                "indexes": [
                    models.Index(
                        fields=["visit_time", "country_code"],
                        name="visit_logs_visit_t_4b891f_idx",
                    ),
                    models.Index(
                        fields=["visit_time", "page_visited"],
                        name="visit_logs_visit_t_474bee_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "visit_time"],
                        name="visit_logs_ip_addr_5c8a96_idx",
                    ),
                ],
            },
        ),
    ]
