# Generated by Django 5.2.4 on 2025-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanpham",
            name="loai_san_pham",
        ),
        migrations.AddField(
            model_name="sanpham",
            name="loai_san_pham",
            field=models.ManyToManyField(
                blank=True, related_name="san_phams", to="core.loaisanpham"
            ),
        ),
    ]
