# Generated by Django 5.2.4 on 2025-09-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_sanpham_loai_san_pham_sanpham_loai_san_pham"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanPhamLoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "loai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.loaisanpham",
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sanpham"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("san_pham", "loai")},
            },
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="loai_san_pham",
            field=models.ManyToManyField(
                blank=True,
                related_name="san_phams",
                through="core.SanPhamLoai",
                to="core.loaisanpham",
            ),
        ),
    ]
